import { useForm } from 'react-hook-form'
import { useState } from 'react'
import { motion } from 'framer-motion'

type TwoFactorInput = {
  code: string
}

export function TwoFactorPage() {
  const { register, handleSubmit, formState: { errors } } = useForm<TwoFactorInput>()
  const [isLoading, setIsLoading] = useState(false)

  const onSubmit = async (values: TwoFactorInput) => {
    setIsLoading(true)
    await new Promise(resolve => setTimeout(resolve, 1500))
    console.log('2fa verify', values)
    setIsLoading(false)
  }

  return (
    <div className="space-y-6">
      <div className="text-center">
        <div className="inline-flex h-12 w-12 items-center justify-center rounded-xl bg-emerald-500/10 text-emerald-500 mb-4 transition-transform hover:scale-110">
          <svg className="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" /></svg>
        </div>
        <h1 className="text-3xl font-bold tracking-tight text-white">Secondary Shield</h1>
        <p className="mt-2 text-slate-400">Enter the 6-digit authentication token generated by your mobile device.</p>
      </div>

      <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
        <div className="space-y-2">
          <div className="flex justify-center">
            <input 
              {...register('code', { required: true, minLength: 6, maxLength: 6 })} 
              maxLength={6}
              className="w-full max-w-[240px] rounded-2xl border border-white/10 bg-white/5 py-4 text-center text-3xl font-bold tracking-[0.5em] text-emerald-400 outline-none focus:border-emerald-500/50 focus:ring-4 focus:ring-emerald-500/10 transition-all font-mono" 
              placeholder="000000" 
            />
          </div>
          <p className="text-center text-xs text-slate-500">Token expires in 30 seconds</p>
        </div>

        <button 
          type="submit" 
          disabled={isLoading}
          className="w-full rounded-2xl bg-emerald-500 py-3 font-bold text-white shadow-[0_0_20px_rgba(16,185,129,0.3)] transition-all hover:bg-emerald-400 hover:shadow-[0_0_25px_rgba(16,185,129,0.5)] active:scale-[0.98] disabled:opacity-70"
        >
          {isLoading ? "Verifying Shield..." : "Unlock Clinical Access"}
        </button>
      </form>

      <div className="text-center pt-2">
        <button type="button" className="text-sm font-medium text-slate-400 hover:text-white transition-colors">
          Facing issues? Try backup codes
        </button>
      </div>
    </div>
  )
}